# - name: apply basic and common roles
#   strategy: debug
#   hosts: ci
#   pre_tasks:
#     - name: Pull in sensitive variables
#       include_vars: "group_vars/passwords-{{ site_name }}.yml"
#     - name: Inform the team of the start
#       slack:
#         msg: "Starting CI deployment for {{ site_name }} on {{ inventory_hostname }}. This baby has {{ ansible_processor_count }} CPUs and {{ ansible_memory_mb.real.total // 1000 }} GB of RAM "
#         channel: "{{ slack_channel}}" # coderade # the channel is encoded in the token.
#         color: normal
#         link_names: 0
#         token: "{{ slack_token }}"
#         username: "Orchy McConfigface on {{ inventory_hostname }}"
#       tags:
#         - slack
#   roles:
#     # - {role: certificates, become: true, tags: certificates}
#     # - {role: AAROC.harden-ssh, become: true, tags: harden-ssh}
#     # - {role: ansible-role-docker, become: true, vagrant: no, docker-py: yes, tags: docker}
#   post_tasks:
#     - name: Inform the team of successful base
#       slack:
#         channel: "{{ slack_channel }}" # the channel is encoded in the token.
#         color: good
#         link_names: 0
#         token: "{{ slack_token }}"
#         username: "Orchy McConfigface on {{ inventory_hostname }}"
#         attachments:
#           - text: "CI base has been applied"
#             fallback: "roles run : bootstrap, certificates, harden-ssh "
#             # Sci-GaIA logo
#             thumb_url: "https://avatars3.githubusercontent.com/u/13150330"
#             footer: "{{ site-name }} Jenkins setup"
#             fields:
#               # - title: ":pray:  bootstrap"
#               #   value: ":item_done:"
#               #   short: true
#               # - title: ":cop: certificates"
#               #   value: ":item_done:"
#               #   short: true
#               - title: ":triumph: harden-ssh"
#                 value: ":item_done:"
#                 short: true
#               # - title: ":whale: docker"
#               #   value: ":item_done:"
#       tags:
#         - slack

- name: Make CI server
  strategy: debug
  hosts: ci
  remote_user: ansible
  vars:
    - date: "{{ lookup('pipe','date +%Y%m%d-%H%M') }}"
  pre_tasks:
    - include_vars: "group_vars/passwords-{{ site_name }}.yml"
    - name: inform the team that jenkins config will start
      slack:
        msg: "Starting CI deployment for {{ site_name }} on {{ inventory_hostname }}. This baby has {{ ansible_processor_count }} CPUs and {{ ansible_memory_mb.real.total // 1000 }} GB of RAM "
        color: good
        link_names: 0
        token: "{{ slack_token }}"
        username: "Orchy McConfigface on {{ inventory_hostname }}"
      tags:
        - slack
  post_tasks:
    - name: inform the  team that Jenkins config is done.
      slack:
        msg: "CI  server is up. Please go check it."
        # channel: coderade # the channel is encoded in the token.
        color: good
        link_names: 0
        token: "{{ slack_token }}"
        username: "Orchy McConfigface on {{ inventory_hostname }}"
      tags:
        - slack
  roles:
    - {role: hackfest-ci-jenkins-role, become: true, tags: jenkins}
